from django.urls import path
from .api_views import (
    AddStockAPIView,
    CountryListAPIView,
    PortfolioAnalyticsAPIView,
    SectorByCountryAPIView,
    StockBySectorAPIView,
)
from .views import (
    SignupView,
    LoginView,
    LogoutView,
    ForgotPasswordView,
    MeView,
    StockListCreateView,
    StockUniverseRebuildView,
    PortfolioListCreateView,
    PortfolioView,
    PortfolioAddStockView,
    PortfolioRemoveStockView,
    PortfolioTotalView,
    SectorListView,
    StocksBySectorView,
    StockDetailsView,
    StockForecastView,
    MetalsAnalysisView,
    BitcoinAnalysisView,
    AssetComparisonView,
    PortfolioAnalyticsView,
    PortfolioMLAnalysisView,
)
from .prompt_views import (
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    AuthSignupView,
    CryptoForecastPromptView,
    MetalsHistoryPromptView,
    PortfolioDetailPromptView,
    PortfolioListCreatePromptView,
    PortfolioRiskClustersPromptView,
    PortfolioTopDiscountPromptView,
    PortfolioTopGrowthPromptView,
    StockDetailPromptView,
    StockListCreatePromptView,
    StockSearchPromptView,
)


urlpatterns = [
    path("auth/signup/", AuthSignupView.as_view(), name="auth-signup"),
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/logout/", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/me/", AuthMeView.as_view(), name="auth-me"),
    path("portfolios/", PortfolioListCreatePromptView.as_view(), name="portfolios-prompt"),
    path("portfolios/<int:portfolio_id>/", PortfolioDetailPromptView.as_view(), name="portfolio-detail-prompt"),
    path("portfolios/<int:portfolio_id>/top-discount/", PortfolioTopDiscountPromptView.as_view(), name="portfolio-top-discount"),
    path("portfolios/<int:portfolio_id>/top-growth/", PortfolioTopGrowthPromptView.as_view(), name="portfolio-top-growth"),
    path("portfolios/<int:portfolio_id>/risk-clusters/", PortfolioRiskClustersPromptView.as_view(), name="portfolio-risk-clusters"),
    path("metals/history/", MetalsHistoryPromptView.as_view(), name="metals-history-prompt"),
    path("crypto/btc/forecast/", CryptoForecastPromptView.as_view(), name="crypto-forecast-prompt"),
    path("stocks/search/", StockSearchPromptView.as_view(), name="stock-search-prompt"),
    path("stocks/<int:stock_id>/", StockDetailPromptView.as_view(), name="stock-detail-prompt"),
    path("countries/", CountryListAPIView.as_view(), name="countries"),
    path("sectors/<int:country_id>/", SectorByCountryAPIView.as_view(), name="sectors-by-country"),
    path("sectors/<int:sector_id>/stocks/", StockBySectorAPIView.as_view(), name="stocks-by-sector-id"),
    path("add-stock/", AddStockAPIView.as_view(), name="add-stock"),
    path(
        "portfolio/<int:portfolio_id>/analytics/",
        PortfolioAnalyticsAPIView.as_view(),
        name="portfolio-analytics-by-id",
    ),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("me/", MeView.as_view(), name="me"),
    path("stocks/", StockListCreatePromptView.as_view(), name="stocks-prompt"),
    path("legacy/stocks/", StockListCreateView.as_view(), name="stocks"),
    path(
        "stocks/rebuild-universe/",
        StockUniverseRebuildView.as_view(),
        name="stocks-rebuild-universe",
    ),
    path("sectors/", SectorListView.as_view(), name="sectors"),
    path(
        "stocks/by-sector/<str:sector_name>/",
        StocksBySectorView.as_view(),
        name="stocks-by-sector",
    ),
    path(
        "stocks/details/<str:symbol>/",
        StockDetailsView.as_view(),
        name="stock-details",
    ),
    path(
        "stocks/forecast/<str:symbol>/",
        StockForecastView.as_view(),
        name="stock-forecast",
    ),
    path("analysis/metals/", MetalsAnalysisView.as_view(), name="metals-analysis"),
    path("analysis/bitcoin/", BitcoinAnalysisView.as_view(), name="bitcoin-analysis"),
    path("analysis/compare/", AssetComparisonView.as_view(), name="asset-comparison"),
    path("portfolio/", PortfolioView.as_view(), name="portfolio"),
    path("legacy/portfolios/", PortfolioListCreateView.as_view(), name="portfolios"),
    path("portfolio/add/", PortfolioAddStockView.as_view(), name="portfolio-add"),
    path("portfolio/remove/", PortfolioRemoveStockView.as_view(), name="portfolio-remove"),
    path("portfolio/total/", PortfolioTotalView.as_view(), name="portfolio-total"),
    path("portfolio/analytics/", PortfolioAnalyticsView.as_view(), name="portfolio-analytics"),
    path("portfolio/analysis/", PortfolioMLAnalysisView.as_view(), name="portfolio-ml-analysis"),
]
