# Generated by Django 5.2.12 on 2026-03-05 07:30

import django.db.models.deletion
from django.db import migrations, models


def map_existing_stock_sectors(apps, schema_editor):
    Country = apps.get_model("portfolio", "Country")
    Sector = apps.get_model("portfolio", "Sector")
    Stock = apps.get_model("portfolio", "Stock")

    default_country, _ = Country.objects.get_or_create(name="Global", code="GL")

    for stock in Stock.objects.all():
        raw_sector = getattr(stock, "sector", None)
        sector_name = (str(raw_sector).strip() if raw_sector is not None else "") or "UNKNOWN"
        sector_obj, _ = Sector.objects.get_or_create(
            name=sector_name,
            country=default_country,
        )

        # At this step, stock.sector is still a CharField. Store FK id as string
        # so the upcoming AlterField(CharField -> ForeignKey) can convert safely.
        stock.country_id = default_country.id
        stock.sector = str(sector_obj.id)
        stock.save(update_fields=["country", "sector"])


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_name_and_multi_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Unknown Stock', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.country'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='portfolio.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.sector'),
        ),
        migrations.RunPython(map_existing_stock_sectors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.sector'),
        ),
    ]
